#!/bin/bash
p=$(pwd -P)
function compile() {
	gradle build -x checkstyleMain
}
compile
gumtree=gumtree-$(date '+%Y%m%d')-2.1.0-SNAPSHOT
cp build/libs/client.diff-2.1.0-SNAPSHOT.jar ../$gumtree/lib/
cd ..
$gumtree/bin/gumtree webdiff Hello1.pb Hello2.pb
cd -
