#!/bin/bash
function compile() {
	gradle build -x checkstyleMain
}
compile
cd .. > /dev/null
gumtree=gumtree-$(date '+%Y%m%d')-2.1.0-SNAPSHOT
if [ ! -d $gumtree/lib/ ]; then
	gradle build -x checkstyleMain
	unzip dist/build/distributions/$gumtree.zip
fi
cp gen.fbs/build/libs/gen.fbs-2.1.0-SNAPSHOT.jar $gumtree/lib/
